title: Milord
author: Donk
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  FREE GAMBLING IRS EVASION

# social links
twitter_username: twitter is poison
github_username:  github is ok

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
